# ONLY MEANT FOR DEVELOPMENT USE!

services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-my_database}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      DB_SERVER: database
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-my_database}
    depends_on:
      - database
    restart: unless-stopped

volumes:
  pgdata:
