apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale-ingress
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headscale.davidnet.net`)
      kind: Rule
      services:
        - name: headscale-service
          port: 8080
  tls:
    certResolver: letsencrypt