apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: davidnet-backend-ingress-public
  namespace: { { .Release.Namespace } }
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.publicHost }}`)
      kind: Rule
      services:
        - name: davidnet-backend-service
          port: { { .Values.service.port } }
  tls: {}
