apiVersion: v1
kind: Service
metadata:
  name: davidnet-backend-service
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: http
  selector:
    app: davidnet-backend
